# Generated by Django 2.1.5 on 2020-12-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20201228_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
