# Generated by Django 3.1.4 on 2021-01-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_auto_20201228_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercises',
            old_name='splits',
            new_name='focus',
        ),
        migrations.AddField(
            model_name='exercises',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
